export const formatTime = (seconds: number): string => {
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
};

export const getTodayDateString = (): string => {
  return new Date().toISOString().split('T')[0];
};

export const generateMarkdown = (tasks: any[], stats: any): string => {
  const date = getTodayDateString();
  const completedTasks = tasks.filter((t) => t.completed).length;
  const totalTasks = tasks.length;
  
  let md = `# RETROFOCUS LOG - ${date}\n\n`;
  
  md += `## DAILY STATISTICS\n`;
  md += `-------------------\n`;
  md += `- Pomodoros Completed: ${stats.pomodorosCompleted}\n`;
  md += `- Total Focus Time: ${Math.round(stats.totalTimeMinutes)} minutes\n`;
  md += `- Task Completion: ${completedTasks}/${totalTasks}\n\n`;
  
  md += `## TASK LIST\n`;
  md += `------------\n`;
  
  if (tasks.length === 0) {
    md += `(No tasks recorded)\n`;
  } else {
    tasks.forEach(task => {
      const check = task.completed ? '[x]' : '[ ]';
      const pomodoros = task.pomodoros > 0 ? ` (*${task.pomodoros})` : '';
      md += `${check} ${task.text}${pomodoros}\n`;
    });
  }
  
  md += `\n---\nGenerated by RetroFocus TUI`;
  
  return md;
};

export const downloadMarkdown = (content: string, filename: string) => {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};